<?php 
	include('baseUrl.php');
?>
<title>XML Sitemap</title>
<link rel="stylesheet" href="<?php echo $baseUrl; ?>css/bootstrap.css" />
<style type="text/css">
.custab{
    border: 1px solid #ccc;
    padding: 5px;
    margin: 1% 0;
    box-shadow: 3px 3px 2px #ccc;
    transition: 0.5s;
    }
.custab:hover{
    box-shadow: 3px 3px 0px transparent;
    transition: 0.5s;
    }
.table-striped > tbody > tr:nth-of-type(odd) {
  background-color: #eaeaea;
}
</style>
<div class='container'>
<?php 
	echo "
			
			<h1>XML Sitemap</h1><br />
			Generated by <a href='http://www.nafiansyah.com/'>Ghani Fingerstyle</a> SEO plugin, this is an XML Sitemap, meant for consumption by search engines.
			You can find more information about XML sitemaps on <a href='http://indocreator.com'>indocreator.com</a>.
			<br /><br />
			This XML Sitemap Index file contains 7 sitemaps. 
			<br />
			<a href='sitemap_index.xml'><i class='glyphicon glyphicon-hand-up'></i> Sitemap Index</a>
			";
?>
	<table class="table table-striped custab">
		<thead>
			<th>URL</th>
			<th>Prio</th>
			<th>Images</th>
			<th>Ch.Freq.</th>
			<th>Last Mod</th>
		</thead>
		<tbody>
			<tr>
				<td><a href="<?php echo $baseUrl; ?>"><?php echo $baseUrl; ?></a></td>
				<td>100%</td>
				<td>0</td>
				<td>Daily</td>
				<td>---------------</td>
			</tr>
			<?php 
				$SHOW_POST = mysqli_query($connecDB, "SELECT * FROM post ORDER BY idPost DESC")or die(mysql_error());
				while($X = mysqli_fetch_array($SHOW_POST)){
			?>
				<tr>
					<td><a href="<?php echo $baseUrl.$X['seourl']."/".$X['modul']; ?>"><?php echo $baseUrl.$X['seourl']."/".$X['modul']; ?></a></td>
					<td>60%</td>
					<td>
			<?php 
error_reporting(0);
$HTML = <<< HTML
<?php 
	echo $X[isi];
?>
HTML;

$dom = new DOMDocument;
libxml_use_internal_errors(true);
$dom->loadHTML($HTML);
$allElements = $dom->getElementsByTagName('*');
//cho $allElements->length;

$elementDistribution = array();
foreach($allElements as $element) {
    if(array_key_exists($element->tagName, $elementDistribution)) {
        $elementDistribution[$element->tagName] += 1;
    } else {
        $elementDistribution[$element->tagName] = 1;
    }
}
print_r($elementDistribution['img']);

			?>


					</td>
					<td>Weekly</td>
					<td><?php echo $X['tglPost']; ?></td>
				</tr>
			<?php } ?>
		</tbody>	
	</table>
<?php 

//$SHOW_POST_Z = mysqli_query($connecDB, "SELECT * FROM post ORDER BY idPost DESC")or die(mysql_error());
//$Z = mysqli_fetch_array($SHOW_POST_Z);

?>

</div>