<?php 
	include('baseUrl.php');
?>
<title>XML Sitemap</title>
<link rel="stylesheet" href="css/bootstrap.css" />
<style type="text/css">
.custab{
    border: 1px solid #ccc;
    padding: 5px;
    margin: 1% 0;
    box-shadow: 3px 3px 2px #ccc;
    transition: 0.5s;
    }
.custab:hover{
    box-shadow: 3px 3px 0px transparent;
    transition: 0.5s;
    }
.table-striped > tbody > tr:nth-of-type(odd) {
  background-color: #eaeaea;
}
</style>
<div class='container'>
<?php 
	echo "
			
			<h1>XML Sitemap</h1><br />
			Generated by <a href='http://www.nafiansyah.com/'>Ghani Fingerstyle</a> SEO plugin, this is an XML Sitemap, meant for consumption by search engines.
			You can find more information about XML sitemaps on <a href='http://indocreator.com'>indocreator.com</a>.
			<br /><br />
			This XML Sitemap Index file contains 7 sitemaps. 
			<br />
			<a href='sitemap_index.xml'><i class='glyphicon glyphicon-hand-up'></i> Sitemap Index</a>
			";
?>
	<table class="table table-striped custab">
		<thead>
			<th>URL</th>
			<th>Prio</th>
			<th>Images</th>
			<th>Ch.Freq.</th>
			<th>Last Mod</th>
		</thead>
		<tbody>
			<?php 
				$SHOW_POST = mysqli_query($connecDB, "SELECT * FROM page ORDER BY idPage DESC")or die(mysql_error());
				while($X = mysqli_fetch_array($SHOW_POST)){
			?>
				<tr>
					<td><a href="<?php echo $baseUrl."p/".$X['url']; ?>"><?php echo $baseUrl."p/".$X['url']; ?></a></td>
					<td>20%</td>
					<td>0</td>
					<td>Weekly</td>
					<td><?php echo $X['date']; ?></td>
				</tr>
			<?php } ?>
		</tbody>	
	</table>
</div>